# Generated by Django 2.1.3 on 2019-02-07 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190207_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='stu_num',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
