# Generated by Django 2.1.3 on 2019-02-08 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190207_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar_url',
            field=models.CharField(default='http://storage.haishionline.com/image/avatar/default.jpg', max_length=200),
        ),
    ]
