# Generated by Django 2.1.3 on 2019-02-19 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_userprofile_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='avatar_url',
        ),
    ]
