# Generated by Django 2.1.3 on 2019-02-20 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_userprofile_avatar_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='identity',
        ),
    ]
