# Generated by Django 2.1.3 on 2019-06-09 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_userprofile_identity'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('teacher', '老师'), ('student', '学生')], default='student', max_length=15),
        ),
    ]
