# Generated by Django 2.1.3 on 2019-01-11 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='course',
        ),
    ]
