# Generated by Django 2.1.3 on 2019-01-31 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_commentnotification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentnotification',
            old_name='render',
            new_name='sender',
        ),
    ]
