# Generated by Django 2.1.3 on 2019-02-06 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_auto_20190131_1354'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentnotification',
            options={'ordering': ('-created',), 'verbose_name': '评论通知', 'verbose_name_plural': '评论通知'},
        ),
    ]
