# Generated by Django 2.1.3 on 2019-01-11 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_videowatchprogress'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videowatchprogress',
            options={'verbose_name': '视频观看进度', 'verbose_name_plural': '视频观看进度'},
        ),
    ]
