# Generated by Django 2.1.3 on 2019-01-12 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0004_auto_20190111_1407'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('deadline', models.CharField(max_length=4)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('classgrade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.ClassGrade')),
                ('students', models.ManyToManyField(blank=True, related_name='yet_sign_in', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='create_sign_in', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '签到',
                'verbose_name_plural': '签到',
                'ordering': ('-created',),
            },
        ),
    ]
