# Generated by Django 2.1.3 on 2019-01-12 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_signin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signin',
            name='code',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='signin',
            name='deadline',
            field=models.CharField(max_length=10),
        ),
    ]
