# Generated by Django 2.1.3 on 2019-01-12 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20190112_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signin',
            name='deadline',
            field=models.CharField(max_length=10, verbose_name='有效分钟'),
        ),
    ]
