# Generated by Django 2.1.3 on 2019-02-06 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_signin_students_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='classgrade',
            name='code',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='邀请码'),
        ),
    ]
