# Generated by Django 2.1.3 on 2019-04-30 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_course_view_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='course',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='play_count',
            new_name='view_count',
        ),
        migrations.RemoveField(
            model_name='course',
            name='view_count',
        ),
        migrations.RemoveField(
            model_name='video',
            name='chapter',
        ),
        migrations.AddField(
            model_name='course',
            name='img_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_videos', to='courses.Course'),
        ),
        migrations.AddField(
            model_name='video',
            name='img_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='overview',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Chapter',
        ),
    ]
