# Generated by Django 2.1.3 on 2019-05-02 16:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0015_auto_20190430_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='study_users',
            field=models.ManyToManyField(blank=True, related_name='study_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
