# Generated by Django 2.1.3 on 2019-05-05 16:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0018_auto_20190503_0225'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClassGrade',
            new_name='CourseClass',
        ),
        migrations.RemoveField(
            model_name='signin',
            name='classgrade',
        ),
        migrations.RemoveField(
            model_name='signin',
            name='students',
        ),
        migrations.RemoveField(
            model_name='signin',
            name='user',
        ),
        migrations.AddField(
            model_name='course',
            name='study_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='SignIn',
        ),
    ]
