# Generated by Django 2.1.3 on 2019-01-17 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionbanks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testpaper',
            name='chapter',
        ),
        migrations.AddField(
            model_name='testpaper',
            name='chapter_number',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='singlechoice',
            name='chapter_number',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
