# Generated by Django 2.1.3 on 2019-01-18 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionbanks', '0002_auto_20190117_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singlechoice',
            name='option_a',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='singlechoice',
            name='option_b',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='singlechoice',
            name='option_c',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='singlechoice',
            name='option_d',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='singlechoice',
            name='title',
            field=models.CharField(max_length=128),
        ),
    ]
