# Generated by Django 2.1.3 on 2019-01-18 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionbanks', '0003_auto_20190118_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singlechoice',
            name='option_a',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='singlechoice',
            name='option_b',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='singlechoice',
            name='option_c',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='singlechoice',
            name='option_d',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='singlechoice',
            name='title',
            field=models.TextField(),
        ),
    ]
