# Generated by Django 2.1.3 on 2019-01-19 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionbanks', '0004_auto_20190118_1503'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testpaper',
            options={'ordering': ('-created',), 'verbose_name': '测试试卷', 'verbose_name_plural': '测试试卷'},
        ),
        migrations.AddField(
            model_name='singlechoiceanswer',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
