# Generated by Django 2.1.3 on 2019-02-09 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionbanks', '0006_singlechoice_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='singlechoice',
            name='img',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
